workspace:
  base: /build
  path: /artifacts
pipeline:
  build:
    image: vinchauhan/my-iib:rc
    commands:
      - cd CustomerDatabaseV1
      - goiib clean
      - goiib compile
    environment:
      - LICENSE=accept  
      