workspace:
  base: /artifacts
  path: /repo
pipeline:
  build:
    image: vinchauhan/my-iib:rc
    commands:
      - cd CustomerDatabaseV1
      - export PATH=$PATH:/build/
      - goiib clean
      - goiib compile
    environment:
      - LICENSE=accept  
      